#!/usr/bin/env python3
"""
ForgeGuard AI — Computer Vision Demo Evidence Generator
Produces predefined, validated visual inspection evidence for the synthetic PUMP_001
progressive bearing degradation failure scenario.

CRITICAL: Every output generated by this module is explicitly labeled with:
    "mode": "DEMO"
Never use or present these outputs as real neural network inference.
"""

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

# Add project root to sys.path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from ai.vision.evidence import (
    BoundingRegion,
    VisualEvidence,
    VisualInspectionReport,
)


def get_demo_evidence_normal(
    machine_id: str = "PUMP_001",
    timestamp: str = "2026-10-04T09:30:00Z"
) -> VisualInspectionReport:
    """
    Generate demo visual evidence for healthy baseline operation (Stage 1).
    """
    finding = VisualEvidence(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_BASELINE_001",
        timestamp=timestamp,
        defect_type="NORMAL_OPERATION",
        confidence=0.98,
        severity="NORMAL",
        region=BoundingRegion(x=0.0, y=0.0, width=1.0, height=1.0),
        visual_evidence=(
            "Camera frame shows intact epoxy enamel coating across bearing housing; "
            "labyrinth shaft seal is dry with zero fluid egress; "
            "flexible coupling aligned with zero particulate debris."
        ),
        possible_implication=(
            "Nominal baseline machine appearance; no visual indicators of mechanical "
            "or thermal distress."
        ),
        mode="DEMO"
    )

    return VisualInspectionReport(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_BASELINE_001",
        timestamp=timestamp,
        findings=[finding],
        mode="DEMO"
    )


def get_demo_evidence_incipient(
    machine_id: str = "PUMP_001",
    timestamp: str = "2026-10-04T12:00:00Z"
) -> VisualInspectionReport:
    """
    Generate demo visual evidence for incipient degradation (Stage 2: Grease Weeping & Ingress).
    """
    finding_oil = VisualEvidence(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_INCIPIENT_002",
        timestamp=timestamp,
        defect_type="DEFECT_OIL_LEAK",
        confidence=0.92,
        severity="MEDIUM",
        region=BoundingRegion(x=0.42, y=0.55, width=0.18, height=0.22),
        visual_evidence=(
            "Dark, viscous fluid weeping and droplet trails radiating from the drive-end "
            "labyrinth seal interface onto the pump pedestal baseplate."
        ),
        possible_implication=(
            "Active lubricant seal weeping indicating grease depletion and loss of hydrodynamic "
            "lubrication film in the drive-end bearing cavity."
        ),
        mode="DEMO"
    )

    finding_seal = VisualEvidence(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_INCIPIENT_002",
        timestamp=timestamp,
        defect_type="DEFECT_SEAL_CONTAMINATION",
        confidence=0.88,
        severity="MEDIUM",
        region=BoundingRegion(x=0.40, y=0.50, width=0.15, height=0.16),
        visual_evidence=(
            "Frayed elastomeric seal lip with dark grit and slurry particulate caking "
            "around the shaft entry collar."
        ),
        possible_implication=(
            "Environmental seal barrier compromised; high risk of abrasive particulate ingress "
            "into the bearing raceway accelerating 3-body abrasive wear."
        ),
        mode="DEMO"
    )

    return VisualInspectionReport(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_INCIPIENT_002",
        timestamp=timestamp,
        findings=[finding_oil, finding_seal],
        mode="DEMO"
    )


def get_demo_evidence_severe(
    machine_id: str = "PUMP_001",
    timestamp: str = "2026-10-04T15:30:00Z"
) -> VisualInspectionReport:
    """
    Generate demo visual evidence for severe degradation (Stage 3: Thermal Discoloration & Heavy Leakage).
    """
    finding_thermal = VisualEvidence(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_CRITICAL_003",
        timestamp=timestamp,
        defect_type="DEFECT_THERMAL_DISCOLOR",
        confidence=0.96,
        severity="CRITICAL",
        region=BoundingRegion(x=0.35, y=0.28, width=0.28, height=0.32),
        visual_evidence=(
            "Severe dark brown and blackened thermal discoloration centered on the cast-iron "
            "drive-end bearing housing with visible paint blistering and peeling."
        ),
        possible_implication=(
            "Prolonged extreme internal heat generation (>90°C surface temperature) from severe "
            "metal-to-metal raceway spalling and imminent bearing seizure."
        ),
        mode="DEMO"
    )

    finding_oil = VisualEvidence(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_CRITICAL_003",
        timestamp=timestamp,
        defect_type="DEFECT_OIL_LEAK",
        confidence=0.94,
        severity="HIGH",
        region=BoundingRegion(x=0.40, y=0.52, width=0.24, height=0.26),
        visual_evidence=(
            "Substantial dark grease puddle pooling beneath drive-end bearing housing "
            "with continuous viscous run-off."
        ),
        possible_implication=(
            "Complete failure of labyrinth grease retention; bearing cavity is severely starved "
            "of lubricant."
        ),
        mode="DEMO"
    )

    return VisualInspectionReport(
        machine_id=machine_id,
        image_id=f"IMG_{machine_id}_CRITICAL_003",
        timestamp=timestamp,
        findings=[finding_thermal, finding_oil],
        mode="DEMO"
    )


def generate_demo_visual_evidence(scenario: str = "all") -> Dict[str, Any]:
    """
    Generate structured demo visual evidence dictionary.
    Supported scenarios: 'normal', 'incipient', 'severe', 'all'
    """
    scenarios_map = {
        "normal": get_demo_evidence_normal(),
        "incipient": get_demo_evidence_incipient(),
        "severe": get_demo_evidence_severe()
    }

    if scenario in scenarios_map:
        return scenarios_map[scenario].to_dict()

    return {
        "machine_id": "PUMP_001",
        "mode": "DEMO",
        "description": "Synthetic visual inspection timeline demonstrating progressive bearing failure.",
        "scenarios": {
            "stage_1_normal": get_demo_evidence_normal().to_dict(),
            "stage_2_incipient": get_demo_evidence_incipient().to_dict(),
            "stage_3_severe": get_demo_evidence_severe().to_dict()
        }
    }


def main():
    parser = argparse.ArgumentParser(
        description="ForgeGuard AI Computer Vision Demo Evidence CLI"
    )
    parser.add_argument(
        "--scenario", "-s",
        choices=["normal", "incipient", "severe", "all"],
        default="all",
        help="Inspection scenario to simulate (default: all)"
    )
    parser.add_argument(
        "--output", "-o",
        default=None,
        help="Path to save output JSON evidence (e.g. results/visual_demo_evidence.json)"
    )
    args = parser.parse_args()

    print("=" * 78)
    print("  FORGEGUARD AI — COMPUTER VISION DEMO EVIDENCE GENERATOR")
    print("  Mode: DEMO / SYNTHETIC SCENARIO (Non-Real Model Inference)")
    print("=" * 78)

    evidence_data = generate_demo_visual_evidence(args.scenario)

    if args.scenario != "all":
        print(f"\n[+] Inspection Report for scenario: '{args.scenario}'")
        print(f"  Machine ID:     {evidence_data.get('machine_id')}")
        print(f"  Image ID:       {evidence_data.get('image_id')}")
        print(f"  Timestamp:      {evidence_data.get('timestamp')}")
        print(f"  Visual Status:  {evidence_data.get('overall_visual_status')}")
        print(f"  Max Severity:   {evidence_data.get('max_severity')}")
        print(f"  Mode:           {evidence_data.get('mode')}")
        print(f"  Summary:        {evidence_data.get('summary')}")
        print("\n  Visual Findings:")
        for idx, f in enumerate(evidence_data.get("findings", []), 1):
            print(f"    {idx}. [{f.get('severity')}] {f.get('defect_type')} (Confidence: {f.get('confidence'):.2f})")
            print(f"       Region:         {f.get('region')}")
            print(f"       Observation:    {f.get('visual_evidence')}")
            print(f"       Interpretation: {f.get('possible_implication')}\n")
    else:
        print("\n[+] Full Visual Degradation Progression Scenarios Generated:")
        for stage_name, stage_data in evidence_data.get("scenarios", {}).items():
            print(f"\n  >> {stage_name.upper()} [{stage_data.get('max_severity')}]:")
            print(f"     Image ID: {stage_data.get('image_id')} | Status: {stage_data.get('overall_visual_status')}")
            print(f"     Summary:  {stage_data.get('summary')}")
            for f in stage_data.get("findings", []):
                print(f"     * {f.get('defect_type')}: {f.get('visual_evidence')}")

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(evidence_data, f, indent=2)
        print(f"\n[+] Demo visual evidence saved to: {out_path.resolve()}")

    print("=" * 78 + "\n")


if __name__ == "__main__":
    main()
